[PHP]
memory_limit = 512M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
max_input_time = 300
expose_php = Off
date.timezone = Africa/Luanda

; Realpath Cache
realpath_cache_size = 4096k
realpath_cache_ttl = 600

; Session
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_secure = 0
session.gc_maxlifetime = 7200

; Error reporting for production/container
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /var/log/php/error.log
