server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /var/www/public;

    index index.php index.html;

    client_max_body_size 64M;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;

    # Healthcheck endpoints
    location /health {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'OK';
    }

    # Static Assets Caching
    location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|woff|woff2|svg)$ {
        expires 365d;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }
}
